function extract_triangles(in_fname, upstream_slice, downstream_slice)
% Purpose:  This function will take the storage time distributions created
%           by deposit_storage_time.m and generate separate files
%           containing all the distributions from the 'analyzed' time
%           period of the model for the upstream reach, downstream reach, 
%           and both reaches.
%           Inputs:     the extreme downstream slice from each reach
%                       the file name
%                       the input files 
%           Outputs:    Storage time and age distributions for point bar
%                       and floodplain deposits for each reach and both
%                       reaches combined
%           
%           This code is hard coded to remove the final few thousand years
%           of simulation time and to select slices generated by a computer
%           with much more RAM (thus creating only 40 slices)
% Author:   Tobias Hasse tobiack@udel.edu
% Date:     edited October 2021, written 2016 - 2019

% % cd(uigetdir)
%% load storage time triangles, save them to work on with other files
 
% distr_3chan* available at https://doi.org/10.5281/ZENODO.5651874. 
% load('distr_3chan_211k_30yr_16.mat')
load(sprintf('%s%d.mat', in_fname, upstream_slice ) )
pt_bar_dist(  flipud(eye(size(pt_bar_dist  ))==1))=0;  % removes terrace
pt_bar_dist_u = pt_bar_dist;    % _u for upstream
vert_dist_u =   vert_dist;
pb_age_dist_u = pb_age_dist;
vd_age_dist_u = vd_age_dist;

% distr_3chan* available at https://doi.org/10.5281/ZENODO.5651874. 
% load('distr_3chan_211k_30yr_36.mat')
load(sprintf('%s%d.mat', in_fname, downstream_slice ) ) 
% other_data_3chan* available at https://doi.org/10.5281/ZENODO.5651874. 
% load('other_data_3chan_211k_30yr_36.mat')
load(sprintf('other_data_3chan_211k_30yr_%d.mat', downstream_slice ) ) 
% make upstream and downstream variables
pt_bar_dist(  flipud(eye(size(pt_bar_dist  ))==1))=0;  % removes terrace

pt_bar_dist_a = pt_bar_dist;    % _a for all upstream and downstream
vert_dist_a   = vert_dist;
pb_age_dist_a = pb_age_dist;
vd_age_dist_a = vd_age_dist;

pt_bar_dist_d = pt_bar_dist_a - pt_bar_dist_u; % _d for downstream
vert_dist_d =   vert_dist_a - vert_dist_u;
pb_age_dist_d = pb_age_dist_a - pb_age_dist_u;
vd_age_dist_d = vd_age_dist_a - vd_age_dist_u;

% [cdata, cdata2]=cmapsTRA;
%%
descr=['Upstream: These values are the 120-205 ky (4000-6845) storage'...
    ' times for vertical (flood) deposits, point bar deposits.'...
    ' computed within extract_triangles.m October 2021.'...
    ' Formerly plot_figs_2019 July 2019 MAC'];
pt_bar_dist = pt_bar_dist_u(1:6845,end-6844:end);
vert_dist   = vert_dist_u(1:6845,end-6844:end);
vd_age_dist = vd_age_dist_u(1:6845,end-6844:end);
pb_age_dist = pb_age_dist_u(1:6845,end-6844:end);
fname='TRH 205k upstream storage triangles.mat';
save(fname,'descr',...
     'pt_bar_dist','vert_dist','vd_age_dist','pb_age_dist',...
     '-v7.3')

%%
descr=['Downstream: These values are the 120-205 ky (4000-6845) storage'...
    ' times for vertical (flood) deposits, point bar deposits.'...
    ' computed within extract_triangles.m October 2021.'...
    ' Formerly plot_figs_2019 July 2019 MAC'];
pt_bar_dist = pt_bar_dist_d(1:6845,end-6844:end);
vert_dist   = vert_dist_d(1:6845,end-6844:end);
vd_age_dist = vd_age_dist_d(1:6845,end-6844:end);
pb_age_dist = pb_age_dist_d(1:6845,end-6844:end);
fname='TRH 205k downstream storage triangles.mat';
save(fname,'descr',...
     'pt_bar_dist','vert_dist','vd_age_dist','pb_age_dist',...
     '-v7.3')
%%
descr=['up and downstream: These values are the 120-205 ky (4000-6845)'...
    ' storage times for vertical (flood) deposits, point bar deposits.'...
    ' computed within extract_triangles.m October 2021.'...
    ' Formerly plot_figs_2019 July 2019 MAC'];
pt_bar_dist = pt_bar_dist_a(1:6845,end-6844:end);
vert_dist   = vert_dist_a(1:6845,end-6844:end);
vd_age_dist = vd_age_dist_a(1:6845,end-6844:end);
pb_age_dist = pb_age_dist_a(1:6845,end-6844:end);
fname='TRH 205k up & downstream storage triangles.mat';
save(fname,'descr','pt_bar_dist','vert_dist','vd_age_dist',...
    'pb_age_dist','-v7.3')

end
